title: Kailyn Brown | Portfolio
description: creative developer — building interfaces and breaking conventions
author: Kailyn Brown
email: your.email@example.com
baseurl: "/portfolio"
url: "https://kailyn0215.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE